### ISSUE TITLE
Sept 29 Meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#12]
### Attendance:
- [x] Daniel
- [x] Jonny
- [x] Sam
- [x] Sophie

### To-Do Before Meeting
- write down at least 10 functional requirements 

### Agenda
- [x] share/present individual requirements
- [x] delete duplicate requirements
- [x] finalize list of requirements
- [x] jonny and sophie switch sections (jonny wants to do use case)

### To-Do After Meeting
- work on individual parts for SRS (by end of day Tuesday)
- TA meeting on Monday 3:30 - ask about POC(feasibility/marking)
- peer review due Sunday Oct 8
