### ISSUE TITLE
Nov 22 - Meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#130]
### Attendance:
- [x] Daniel
- [x] Jonny
- [x] Sam
- [x] Sophie

### Agenda:
- [x] plan going forward
- [x] update prof supervisor on Gitlab
- [x] data update from Stu

### To-do:
- read studies before meeting with Stu
- come prepared to talk about data gathering

**Comment by sophiefillion** [comment]
Notes:
- meeting with Stu on Tuesday at 12:30 (will talk about consistent meeting time then)
- daniel and jonny focus on fullstack
- sam and sophie focus on AI
