### ISSUE TITLE
Sept 25 meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#4]
### To-Do Before Meeting
- [x] review problem statement and dev/POC plan documents

### Agenda
- [x] complete POC section
- [x] raise any issues with current state of problem statement and dev/POC plan documents
- [ ] discuss SRS deliverable and how to split each section
- [ ] create new doc for SRS deliverable

### Attendance:
- [x] Daniel
- [ ] Jonny
- [x] Sam
- [x] Sophie

### To-Do After Meeting
- [ ] transfer to latex and push to git (due tonight)
- [ ] work on assigned tasks for SRS

**Comment by sophiefillion** [comment]
meeting tmr to talk about srs
