### ISSUE TITLE
Oct 4 Meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#46]
### Attendance:
- [x] Daniel
- [x] Jonny
- [ ] Sam (sick)
- [x] Sophie

### Agenda:
- [x] update on SRS document
- [x] pull request for specific group? (due today)
- [x] review functional requirements (see capstone intelligence example)

### To-Do After Meeting
- finish SRS (due Friday)
- peer review due Sunday Oct 8?
