### ISSUE TITLE
Oct 18 Meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#90]
### Attendence:
- [x] Daniel
- [x] Jonny
- [x] Sam
- [x] Sophie

### Agenda:
- [x] go over database stuff that we did
- [x] hazard analysis progress and questions
- [ ] make milestones for frontend and backend?

### To-Do After Meeting:
- hazard analysis due Friday
- continue front and back end coding
