### ISSUE TITLE
Oct 23 Meeting

### ISSUE THREAD

**Issue by sophiefillion** [d-akselrod/SweatSmart#98]
### Attendence:
- [x] Daniel
- [x] Jonny
- [x] Sam
- [x] Sophie

### Agenda:
- [x] progress updates
- [ ] figure out deadlines for tasks and what needs to get done asap
- [ ] produce react deadline, decide on which pages need focus
- [ ] discuss data set gathering and organization: labels, sources, etc
- [ ] create specific plan for data collection
- [ ] logo

### To-Do After Meeting:
- peer review issues due tonight
- continue front and back end development
- tests for user endpoints
- get data set for muscle building

**Comment by sammcdonald14** [comment]
Need a lil tutorial on how to add page to react

**Comment by sophiefillion** [comment]
POC:
- profile creation pages (physical attributes + fitness goals)
- get data set for muscle building
- ai workout page

**Comment by sammcdonald14** [comment]
Muscle Building data set ideas brainstorm: 
- workout frequency 
- workout split 
- workout intensity 
- age 
- gender 
- split by day perhaps
